# инкапсуляция и абстракция

class Bond:
    ...
class Stonk:
    ...
class CheckingAccount:
    ...
class SavingAccount:
    ...
class RealEstate:
    ...

class BankAccount(CheckingAccount, SavingAccount):
    ...
class Security(Bond, Stonk):
    ...
class InsurableItem(BankAccount, RealEstate):
    ...
class InterestBearingItem(BankAccount, Security):
    ...

class Asset(BankAccount, RealEstate, Security):
    ...

print(Security.mro())